# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
#archive:
  #replacements:
    #darwin: Darwin
    #linux: Linux
    #windows: Windows
    #386: i386
    #amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: mongey
    name: terraform-provider-acme

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true

  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: true

  disable: false
